# Zonas Agroproductivas Metadata
library(dplyr)

get_zones_metadata <- function() {
  data.frame(
    zone = c(
      "Cordillera Apaneca e Ilamatepec",
      "Valle de Chalchuapa - Candelaria de la Frontera",
      "Valle de Santa Ana - Coatepeque",
      "Valle de Zapotitán",
      "Valle de Atiocoyo Sur",
      "Valle de Ahuachapán Sur (Cara Sucia-Garita Palmera)",
      "Valle de Atiquizaya",
      "Valle de Sonsonate",
      "Valle del Lago de Güija y Guajoyo",
      "Cordillera del Bálsamo",
      "Valle de Quezaltepeque",
      "Valle de Cuscatlán (Cojutepeque-San Rafael Cedros)",
      "Valle de Chalatenango",
      "Valle de Nueva Concepción",
      "Valle Medio del Río Lempa",
      "Cordillera Fronteriza Alotepec Metapán",
      "Cordillera Chinchontepec",
      "Valle de Jiboa",
      "Valle de Tecoluca - Bajo Lempa",
      "Valle de Apastepeque - Verapaz",
      "Valle de San Vicente - Acahuapa",
      "Valle de Ilobasco",
      "Valle de Sensuntepeque",
      "Valle Costero de Comalapa - Litoral de La Paz",
      "Cordillera de Tecapa-Chinameca",
      "Cordillera de Cacahuatique",
      "Valle de San Miguel",
      "Valle de Jiquilisco - Bahia de Jiquilisco",
      "Valle de Usulután",
      "Valle del Bajo Lempa Oriental",
      "Valle de El Tránsito - San Rafael Oriente",
      "Valle de La Unión",
      "Valle de Jocoro - El Sauce",
      "Valle de Gotera",
      "Valle Costero de Chirilagua - El Tamarindo"
    ),
    region = c(
      "Occidental", "Occidental", "Occidental", "Central", "Central", 
      "Occidental", "Occidental", "Occidental", "Occidental", "Central", 
      "Central", "Central", "Central", "Central", "Central", 
      "Central", "Paracentral", "Paracentral", "Paracentral", "Paracentral", 
      "Paracentral", "Paracentral", "Paracentral", "Paracentral", "Oriental", 
      "Oriental", "Oriental", "Oriental", "Oriental", "Oriental", 
      "Oriental", "Oriental", "Oriental", "Oriental", "Oriental"
    ),
    crops = c(
      "Café, aguacate, cítricos, jocote, durazno, manzana rosa, níspero, hortalizas, granos básicos, caña de azúcar, cacao, apicultura",
      "Caña de azúcar, café, cítricos, granos básicos (maíz, frijol, sorgo, arroz), ganadería",
      "Café, caña de azúcar, hortalizas, granos básicos, actividades agroindustriales",
      "Hortalizas, frutas, granos básicos (bajo riego), caña de azúcar, ganadería",
      "Caña de azúcar, granos básicos (maíz, frijol, arroz), hortalizas, ganadería, acuicultura, fruticultura",
      "Coco, ganadería, granos básicos (maíz, frijol, sorgo), acuicultura, frutales tropicales, hortalizas, pesca artesanal",
      "Café, granos básicos, hortalizas, ganadería, fruticultura",
      "Caña de azúcar, cacao, banano, coco, limón, naranja, café, mango, plátano, hortalizas, apicultura, granos básicos",
      "Granos básicos (maíz, frijol, sorgo), ganadería, horticultura, sistemas silvopastoriles, acuicultura, turismo rural",
      "Café de altura, cacao, bálsamo, aguacate Hass, cítricos, plátano, frutas tropicales, apicultura, hortalizas de altura, plantas ornamentales",
      "Granos básicos, hortalizas, ganadería, agroindustria, producción avícola",
      "Hortalizas, frutas, granos básicos, café, ganadería de pequeña escala, desarrollo de cadenas de valor",
      "Hortalizas de altura, café, ganadería, frutas, apicultura, granos básicos, sistemas agroforestales",
      "Granos básicos, hortalizas, melón, sandía, ganadería, agricultura bajo riego, desarrollo agroindustrial",
      "Granos básicos, ganadería, acuicultura, frutales, agricultura bajo riego, adaptación al cambio climático",
      "Ganadería de carne y doble propósito, producción lechera, café de altura, aguacate, cítricos, granos básicos, apicultura, silvopastoriles",
      "Café de altura, cacao, aguacate, cítricos, plátano, musáceas, hortalizas de altura, granos básicos, ganadería de doble propósito",
      "Caña de azúcar, granos básicos, hortalizas, frutales, ganadería, agroindustria alimentaria, acuicultura",
      "Arroz, caña de azúcar, granos básicos, pesca, acuicultura, ganadería, coco, marañón, frutales tropicales, hortalizas",
      "Hortalizas, granos básicos, frutas, ganadería, apicultura, caña de azúcar, agroindustria de pequeña escala",
      "Hortalizas, maíz, frijol, arroz, caña de azúcar, frutas tropicales, cítricos, ganadería de doble propósito, apicultura",
      "Granos básicos (maíz, frijol, sorgo), hortalizas, ganadería, apicultura, agroindustria artesanal",
      "Ganadería, granos básicos, apicultura, frutas, sistemas silvopastoriles, agroforestería",
      "Coco, marañón, mango, plátano, sandía, melón, caña de azúcar, granos básicos, ganadería, camaronicultura, acuicultura",
      "Café de altura, aguacate, cacao, cítricos, hortalizas, granos básicos, apicultura, frutales, sistemas agroforestales",
      "Café de altura, cacao, aguacate, granos básicos, hortalizas de montaña, apicultura, ganadería sostenible, silvopastoriles",
      "Caña de azúcar, granos básicos, ganadería, horticultura, frutales, agroindustria, café, avicultura, acuicultura",
      "Coco, cacao, caña de azúcar, granos básicos, ganadería, acuicultura, camaronicultura, pesca artesanal, frutales tropicales",
      "Café, caña de azúcar, granos básicos, hortalizas, frutas, cacao, ganadería, procesamiento agroindustrial",
      "Granos básicos, caña de azúcar, acuicultura, ganadería, frutales (coco, plátano, papaya), hortalizas, sandía, melón",
      "Caña de azúcar, granos básicos, hortalizas, frutales, ganadería, acuicultura, agroindustria",
      "Ganadería, marañón, coco, mango, sandía, granos básicos, ajonjolí, acuicultura, pesca, bosques costeros",
      "Ganadería, granos básicos, apicultura, frutales, sistemas silvopastoriles, agricultura resiliente",
      "Ganadería, granos básicos, café de altura, apicultura, frutales, agroforestería",
      "Camaronicultura, acuicultura, pesca artesanal, coco, marañón, mango, sandía, melón, ganadería de carne, apicultura"
    ),
    competitiveness = c(
      "Suelos volcánicos de alta fertilidad, altitudes entre 800 y 2,300 msnm, clima favorable para cultivos de altura, recursos hídricos, reconocimiento internacional del café Apaneca-Ilamatepec, potencial para turismo rural.",
      "Amplias áreas mecanizables, cercanía a la frontera con Guatemala, infraestructura vial internacional, presencia de agroindustria azucarera, mano de obra agrícola.",
      "Excelente conectividad logística, proximidad a la Carretera Panamericana, servicios financieros, agroindustria establecida, centros de acopio y mercados de exportación.",
      "Uno de los valles agrícolas más fértiles del país, infraestructura de riego, topografía favorable para mecanización, cercanía al AMSS, acceso a cadenas de comercialización.",
      "Presencia del Distrito de Riego Atiocoyo Sur, disponibilidad permanente de agua, terrenos aptos para agricultura intensiva, potencial para agroexportación.",
      "Disponibilidad de agua superficial, planicies costeras aptas para mecanización, acceso al litoral Pacífico, pesca artesanal y recursos costeros.",
      "Condiciones climáticas favorables, disponibilidad de mano de obra rural, cercanía a corredores logísticos fronterizos, fortalecimiento de cadenas de valor.",
      "Cercanía al Puerto de Acajutla, infraestructura logística de exportación, agroindustria, conectividad vial, diversidad climática.",
      "Recursos hídricos provenientes de lagos Güija y Guajoyo, planicies para ganadería y agricultura, potencial para riego, sistemas silvopastoriles.",
      "Suelos volcánicos fértiles, altitud 500-1900 msnm, recarga acuífera, cercanía al AMSS, conectividad por Carretera del Litoral y red nacional.",
      "Ubicación estratégica cercana al AMSS, excelente conectividad vial, infraestructura industrial y logística, importante desarrollo avícola.",
      "Condiciones agroclimáticas favorables para producción diversificada, tradición agrícola, potencial para agricultura familiar y desarrollo hortofrutícola.",
      "Diversidad de pisos altitudinales, abundancia de recursos hídricos, potencial para producción orgánica, cercanía a frontera con Honduras.",
      "Amplias planicies agrícolas, agua proveniente del río Lempa y distritos de riego, potencial para mecanización y producción a gran escala.",
      "Recursos hídricos permanentes, potencial para expansión del riego, fertilidad de suelos aluviales, resiliencia al cambio climático.",
      "Áreas disponibles para expansión, cuenca del Lago de Güija, región Trifinio con acceso a Guatemala y Honduras, ganadería y restauración productiva.",
      "Suelos volcánicos fértiles, altitud 500-2180 msnm, recarga acuífera, cercanía a Carretera Panamericana y Litoral, tradición cafetalera.",
      "Amplias planicies, disponibilidad de agua superficial y subterránea, cercanía al Aeropuerto Internacional y Carretera del Litoral, suelos fértiles.",
      "Agua del río Lempa, sistemas de riego, extensas planicies para mecanización, acuicultura y pesca continental, corredores logísticos.",
      "Suelos volcánicos fértiles, recursos hídricos, cercanía a mercados regionales, potencial para agricultura intensiva y diversificación.",
      "Suelos de alta fertilidad de origen volcánico y aluvial, río Acahuapa y fuentes subterráneas, Carretera Panamericana y centros de acopio.",
      "Amplias áreas agrícolas, tradición productiva, mano de obra rural, Carretera Panamericana, encadenamientos agroindustriales.",
      "Tierras para expansión, recursos forestales, conectividad norte del país, resiliencia al cambio climático.",
      "Planicies costeras mecanizables, agua superficial y subterránea, Carretera del Litoral, cercanía al Aeropuerto Internacional, camaronicultura.",
      "Suelos volcánicos de alta fertilidad, altitud 700-1600 msnm, recarga acuífera, tradición cafetalera, paisaje volcánico, conectividad vial.",
      "Cobertura vegetal, recursos hídricos, sistemas agroforestales, restauración productiva, conectividad zona oriental y norte.",
      "Planicies agrícolas, alta mecanización, Carretera Panamericana, centro urbano regional, mano de obra, conectividad con puertos.",
      "Presencia de la Bahía de Jiquilisco (Sitio Ramsar), abundancia de recursos hídricos, camaronicultura, pesca artesanal y agroexportación.",
      "Agua para riego, tradición agrícola, conectividad vial, cercanía a centros de acopio y procesamiento agroindustrial.",
      "Suelos aluviales altamente fértiles, cuenca baja del río Lempa, agricultura intensiva, producción bajo riego, acuicultura.",
      "Cercanía a San Miguel, conectividad logística, tierras agrícolas, encadenamientos agroindustriales y producción comercial.",
      "Cercanía al Puerto de La Unión, acceso al Golfo de Fonseca, potencial logístico para exportación, recursos marino-costeros.",
      "Tierras disponibles, costos competitivos, ganadería sostenible, resiliencia climática.",
      "Recursos hídricos, sistemas agroforestales, conservación productiva, ganadería, apicultura.",
      "Planicies costeras mecanizables, acceso directo al océano Pacífico y Golfo de Fonseca, camaronicultura y pesca, cercanía a Puerto de La Unión."
    ),
    stringsAsFactors = FALSE
  )
}
